name: "Slide"
exports: "mootools-slide.js"
web: "[mooforum.net](http://mooforum.net)"
description: "MooTools Slide Behavior"
license: "[MIT License](http://mootools.net/license.txt)"
copyright: "&copy; [mooforum](http://mooforum.net)"
authors: "[Thomas Allmer](http://mooforum.net)"

author: daKmoR
category: Interface
tags: [animation, gallery, slide]
#docs: http://url.to.docs
#demo: http://url.to.demo
#current: 0.5

sources:
  - Source/Gallery.js
  - Source/Slide.js
  - Source/Line.js
  - Source/Slide.Element.js
  - Source/Slide.Image.js
  - Source/Slide.Div.js
  - Source/Slide.Link.js
  - Source/Slide.Link.Request.js
  - Source/Slide.Pagination.js
  - Source/Behaviors/Behavior.Slide.js
  - Source/Behaviors/Behavior.Line.js
  - Source/Behaviors/Behavior.Slide.Element.js
  - Source/Behaviors/Behavior.Slide.Pagination.js
  - Source/Delegators/Delegator.SlideControls.js
  - Source/Delegators/Delegator.Slide.Show.js